//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimpArena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenamiento
    {
        public int Id { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> pallet { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    }
}
