//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimpArena.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arenaEntities : DbContext
    {
        public arenaEntities()
            : base("name=arenaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacenamiento> Almacenamiento { get; set; }
        public virtual DbSet<Almacenamiento_Inicial> Almacenamiento_Inicial { get; set; }
        public virtual DbSet<CentrifugadorCarga> CentrifugadorCarga { get; set; }
        public virtual DbSet<Cribado> Cribado { get; set; }
        public virtual DbSet<CribadoProceso2> CribadoProceso2 { get; set; }
        public virtual DbSet<InspeccionTamañoGrano> InspeccionTamañoGrano { get; set; }
        public virtual DbSet<InstpeccionConductividad> InstpeccionConductividad { get; set; }
        public virtual DbSet<Pesaje> Pesaje { get; set; }
        public virtual DbSet<PesajeFinal> PesajeFinal { get; set; }
        public virtual DbSet<QuemadodeRecina> QuemadodeRecina { get; set; }
        public virtual DbSet<SeparacionMagneticos> SeparacionMagneticos { get; set; }
        public virtual DbSet<TanqueEnfriamento> TanqueEnfriamento { get; set; }
        public virtual DbSet<Triturado> Triturado { get; set; }
    }
}
