//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimpArena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuemadodeRecina
    {
        public int Id { get; set; }
        public Nullable<decimal> TempInterna { get; set; }
        public Nullable<decimal> TempExterna { get; set; }
        public Nullable<decimal> TempArena { get; set; }
        public Nullable<decimal> AireComprimido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
